### ISSUE TITLE
skyway-sdk を import しているモジュールでのテストがエラーになる

### ISSUE THREAD

**Issue by ta14-u** [ta14-u/inspection-skyway-js-sdk#4]
## 概要
以下のエラーを解決したい
- https://github.com/ta14-u/inspection-skyway-js-sdk/pull/2
> ## 前提
> - 対象ディレクトリ
>   - `examples/large-room/`
> - #1 での結果を受け `RTCPeerConnection` のモックを追加した
> 
> ## `npm run test`  を実行した結果
> - `example-const.ts` のテスト
>   -  `skyway-sdk` を読み込んでいない
>   - テストは PASS する
> - `const.ts` のテスト
>   -  `skyway-sdk` を読み込んでいる 
>   - `TypeError: (0 , __1.createError) is not a function`エラーで失敗する
> 
> 出力
> ```shell
> ▶ npm run test
> 
> > large-room@0.0.0 test
> > jest
> 
>  PASS  src/example-const.test.ts
>  FAIL  src/const.test.ts
>   ● Test suite failed to run
> 
>     TypeError: (0 , __1.createError) is not a function
> 
>       28 |   constructor() {
>       29 |     if (!navigator?.mediaDevices) {
>     > 30 |       throw createError({
>          |                        ^
>       31 |         operationName: 'StreamFactory.constructor',
>       32 |         info: errors.mediaDevicesNotFound,
>       33 |         path: log.prefix,
> 
>       at new StreamFactory (../../packages/core/src/media/factory.ts:30:24)
>       at Object.<anonymous> (../../packages/core/src/media/factory.ts:265:36)
>       at Object.<anonymous> (../../packages/core/src/index.ts:8:1)
>       at Object.<anonymous> (../../packages/room/src/errors.ts:1:1)
>       at Object.<anonymous> (../../packages/room/src/index.ts:1:1)
>       at Object.<anonymous> (src/const.ts:1:1)
>       at Object.<anonymous> (src/const.test.ts:1:1)
> 
> Test Suites: 1 failed, 1 passed, 2 total
> Tests:       1 passed, 1 total
> Snapshots:   0 total
> Time:        4.587 s
> Ran all test suites.
> ```

## 関連 Issue
- https://github.com/ta14-u/inspection-skyway-js-sdk-large-room/issues/5

**Comment by ta14-u** [comment]
SkyWay SDK の新しいバージョンで解決されているかも
- https://github.com/skyway/js-sdk/releases/tag/v1.2.5
